name: Test Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Prepare Android Environment
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Build With Gradle
        run: |
          chmod +x gradlew
          export PYTHON_BIN=$(which python3)
          echo "Using Python: $PYTHON_BIN ($($PYTHON_BIN --version))"
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all -PbuildPython=$PYTHON_BIN
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
